### ISSUE TITLE
Обучение новым сущностям

### ISSUE THREAD

**Issue by vkudyushev** [pullenti/PullentiServer#2]
Добрый день!
Скажите, пожалуйста, как я могу обучить PullEnti выделению новых сущностей? Например, профессия или род деятельности персоны

**Comment by kuk** [comment]
PullEnti работает на правилах, программу нельзя обучить, нужно написать новые правила, обратить, пожалуйста, к автору @konstantin-smith http://pullenti.ru/. На Гитхабе зеркало кода.
